version: 2
updates:
  # Maintain Dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "infrastructure"
    schedule:
      interval: "weekly"
    target-branch: "main"
