name: Post-Commit

on:
  push:
    branches:
      - main

env:
  TERRAFORM_DOCS_VERSION: v0.16.0

jobs:
  collectInputs:
    name: Collect Workflow Inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.directories.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Root Directories
        id: directories
        uses: clowdhaus/terraform-composite-actions/directories@v1.5.0

  postCommitMaxVersion:
    name: Max Terraform Version Post-Commit
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform Min/Max Versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.0.8
      
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ steps.minMax.outputs.maxVersion }}

      - name: Post-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.5.0
        continue-on-error: true
        with:
          args: '--all-files --color always --config .post-commit-config.yaml --show-diff-on-failure'
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}

      - name: Commit Changes
        uses: clowdhaus/terraform-composite-actions/commit@v1.5.0
        with:
          git-branch: 'main'
          github-repository: ${{ github.repository }}
          github-token: ${{ secrets.GIT_HUB_ACTIONS_TOKEN }}
