name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  collectInputs:
    name: Collect Workflow Inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.directories.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Root Directories
        id: directories
        uses: clowdhaus/terraform-composite-actions/directories@v1.5.0

  preCommitMinVersions:
    name: Min Terraform Version Pre-Commit
    needs: collectInputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.1.1
        with:
          directory: ${{ matrix.directory }}
      
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ steps.minMax.outputs.maxVersion }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.5.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*"

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.5.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)"

  preCommitMaxVersion:
    name: Max Terraform Version Pre-Commit
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform Min/Max Versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.1.1
      
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ steps.minMax.outputs.maxVersion }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.5.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
